#!/usr/bin/env python3
"""Provision private service identities and keys without starting either service.

Run as root on the independent witness host. Existing files are validated, never
replaced. Standard output contains only the public pin and permission metadata.
No startup or activation document is generated by this preparation step.
"""

import argparse
import grp
import json
import os
from pathlib import Path
import pwd
import resource
import stat
import subprocess
import sys
from urllib.parse import urlsplit


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def metadata(path, uid, gid, mode, directory=False):
    value = path.lstat()
    kind = stat.S_ISDIR if directory else stat.S_ISREG
    require(kind(value.st_mode), f"Unexpected file type: {path}")
    require(directory or value.st_nlink == 1, f"Linked file rejected: {path}")
    require(value.st_uid == uid and value.st_gid == gid, f"Wrong owner: {path}")
    require(stat.S_IMODE(value.st_mode) == mode, f"Wrong permissions: {path}")
    return {
        "path": str(path),
        "uid": uid,
        "gid": gid,
        "mode": f"{mode:04o}",
        **({} if directory else {"bytes": value.st_size}),
    }


def directory(path, uid, gid, mode=0o700):
    try:
        path.mkdir(mode=mode)
    except FileExistsError:
        pass
    else:
        os.chown(path, uid, gid, follow_symlinks=False)
        os.chmod(path, mode, follow_symlinks=False)
    return metadata(path, uid, gid, mode, directory=True)


def create_private(path, data, uid, gid):
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    try:
        os.fchown(descriptor, uid, gid)
        with os.fdopen(descriptor, "wb", closefd=False) as output:
            output.write(data)
            output.flush()
            os.fsync(descriptor)
    except BaseException:
        path.unlink()
        raise
    finally:
        os.close(descriptor)
    parent = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(parent)
    finally:
        os.close(parent)


def read_private(path, uid, gid, limit):
    metadata(path, uid, gid, 0o600)
    descriptor = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
    with os.fdopen(descriptor, "rb") as source:
        data = source.read(limit + 1)
    require(len(data) <= limit, f"Oversized private file: {path}")
    return data


def secret(path, uid, gid):
    if not path.exists() and not path.is_symlink():
        create_private(path, os.urandom(32), uid, gid)
    data = read_private(path, uid, gid, 32)
    require(len(data) == 32, f"Expected a 32-byte key: {path}")
    return data


def public_key(seed):
    # RFC 8410 PKCS#8 and SubjectPublicKeyInfo wrappers for Ed25519. The seed is
    # passed only through the child process's standard input, never argv/files.
    result = subprocess.run(
        ["openssl", "pkey", "-inform", "DER", "-pubout", "-outform", "DER"],
        input=bytes.fromhex("302e020100300506032b657004220420") + seed,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
        timeout=10,
    )
    prefix = bytes.fromhex("302a300506032b6570032100")
    require(
        result.returncode == 0 and len(result.stdout) == len(prefix) + 32
        and result.stdout.startswith(prefix),
        "OpenSSL could not derive the Ed25519 public key.",
    )
    return result.stdout[len(prefix):].hex()


def account(name):
    try:
        user = pwd.getpwnam(name)
    except KeyError:
        subprocess.run(
            [
                "useradd", "--system", "--user-group", "--no-create-home",
                "--home-dir", "/nonexistent", "--shell", "/usr/sbin/nologin", name,
            ],
            check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        user = pwd.getpwnam(name)
    require(0 < user.pw_uid < 1000, f"Expected a system account: {name}")
    require(user.pw_shell in ("/usr/sbin/nologin", "/sbin/nologin"), f"Login enabled: {name}")
    require(user.pw_dir == "/nonexistent", f"Unexpected home directory: {name}")
    group = grp.getgrgid(user.pw_gid)
    require(group.gr_name == name, f"Expected a dedicated group: {name}")
    require(not group.gr_mem, f"Additional group members rejected: {name}")
    return user


def config(path, value, user):
    if not path.exists() and not path.is_symlink():
        create_private(path, (json.dumps(value, indent=2) + "\n").encode(), user.pw_uid, user.pw_gid)
    existing = json.loads(read_private(path, user.pw_uid, user.pw_gid, 16_384))
    require(existing == value, f"Existing configuration differs; not overwritten: {path}")
    return metadata(path, user.pw_uid, user.pw_gid, 0o600)


def prepare(origin):
    require(os.geteuid() == 0 and sys.platform == "linux", "Run as root on Linux.")
    resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
    os.umask(0o077)
    parsed = urlsplit(origin)
    require(
        parsed.scheme == "https" and parsed.hostname and parsed.path == ""
        and not parsed.username and not parsed.password and not parsed.query
        and not parsed.fragment and origin == origin.strip()
        and not any(ord(c) < 33 or ord(c) == 127 for c in origin),
        "Provide an HTTPS origin without a path, credentials, query, or fragment.",
    )
    # Verify the local key backend before creating accounts or persistent keys.
    public_key(bytes(32))
    witness = account("elo-witness")
    storage = account("elo-storage")
    require(witness.pw_uid != storage.pw_uid and witness.pw_gid != storage.pw_gid, "Accounts must be separate.")
    evidence = [directory(Path("/etc/elo"), 0, 0, 0o755)]
    for user, suffix in ((witness, "witness"), (storage, "storage")):
        for path in (Path(f"/etc/elo/{suffix}"), Path(f"/var/lib/elo-{suffix}"), Path(f"/run/elo-{suffix}")):
            evidence.append(directory(path, user.pw_uid, user.pw_gid))
    signing = Path("/etc/elo/witness/signing-key.bin")
    storage_key = Path("/etc/elo/storage/secret.key")
    pin = {
        "url": origin + "/witness/v1",
        "public_key": public_key(secret(signing, witness.pw_uid, witness.pw_gid)),
        "key_generation": 1,
    }
    secret(storage_key, storage.pw_uid, storage.pw_gid)
    evidence.extend((
        metadata(signing, witness.pw_uid, witness.pw_gid, 0o600),
        metadata(storage_key, storage.pw_uid, storage.pw_gid, 0o600),
        config(Path("/etc/elo/witness/config.json"), {
            "bind": "127.0.0.1:17845", "pin": pin,
            "data": "/var/lib/elo-witness", "signing_key": str(signing),
            "startup_file": "/run/elo-witness/startup.json",
            "activation_file": "/run/elo-witness/activation.json",
            "trusted_loopback_proxy": True,
        }, witness),
        config(Path("/etc/elo/storage/config.json"), {
            "bind": "127.0.0.1:17846", "public_url": origin + "/storage/v1",
            "data": "/var/lib/elo-storage", "secret_key": str(storage_key),
            "max_spaces": 128, "trusted_loopback_proxy": True, "witness": pin,
        }, storage),
    ))
    return {"pin": pin, "permissions": evidence, "services_started": False, "activation_created": False}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--public-origin", required=True)
    arguments = parser.parse_args()
    try:
        print(json.dumps(prepare(arguments.public_origin)))
    except (OSError, RuntimeError, ValueError, subprocess.SubprocessError) as error:
        # Errors contain file names or fixed diagnostics, never private values.
        print(f"Preparation failed: {type(error).__name__}: {error}", file=sys.stderr)
        sys.exit(1)
