#!/usr/bin/env python3
"""Build the static product and legal pages from one maintained English source."""
import html
import hashlib
import json
import re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "landingpage"
try:
    PUBLISHER = json.loads((SITE / "publisher.json").read_text())
except FileNotFoundError:
    raise SystemExit(
        "Missing landingpage/publisher.json. Copy landingpage/publisher.example.json "
        "to landingpage/publisher.json, replace the example publisher details, "
        "then run python3 tools/build_landing.py again."
    ) from None


class PlainDocument(HTMLParser):
    """Preserve paragraphs and useful URLs without an in-app HTML renderer."""
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts = []
        self.href = None

    def handle_starttag(self, tag, attrs):
        if tag in {"p", "h2", "h3", "ul", "ol"}:
            self.parts.append("\n\n")
        elif tag == "li":
            self.parts.append("\n• ")
        elif tag == "br":
            self.parts.append("\n")
        elif tag == "a":
            self.href = dict(attrs).get("href")

    def handle_endtag(self, tag):
        if tag in {"p", "h2", "h3", "ul", "ol"}:
            self.parts.append("\n\n")
        elif tag == "a":
            if self.href and self.href.startswith("https://"):
                self.parts.append(f" ({self.href})")
            self.href = None

    def handle_data(self, data):
        self.parts.append(re.sub(r"\s+", " ", data))

    def text(self):
        return re.sub(r"\n(?:[ \t]*\n)+", "\n\n", "".join(self.parts)).strip()


def esc(value):
    return html.escape(str(value), quote=True)


def contact(kind="support"):
    email = PUBLISHER.get(kind + "_email") or PUBLISHER.get("support_email")
    if not email:
        return '<span class="draft-value">Contact address awaiting publisher confirmation</span>'
    return f'<a href="mailto:{esc(email)}">{esc(email)}</a>'


def company():
    name = PUBLISHER.get("legal_name") or "Publisher name awaiting confirmation"
    address = PUBLISHER.get("address") or "Registered address awaiting confirmation"
    registration = PUBLISHER.get("registration")
    details = f"<br>{esc(registration)}" if registration else ""
    return f"<p>{esc(name)}<br>{esc(address)}{details}</p>"


def brand(css_class):
    return f'''<span class="brand {css_class}"><span class="brand-name">elo<span class="brand-dot">.</span>now</span><svg class="brand-star" xmlns="http://www.w3.org/2000/svg" viewBox="8 8 48 48" width="24" height="24" aria-hidden="true" focusable="false"><path d="M32 14v36M14 32h36M19 19l26 26M19 45l26-26" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></svg></span>'''


ORIGIN = "https://elo.now"
SOCIAL_IMAGE = ORIGIN + "/assets/social-preview.png"


def structured_data(title, description, canonical, legal):
    organization = {"@type": "Organization", "@id": ORIGIN + "/#publisher",
        "name": "9bits", "legalName": PUBLISHER["legal_name"], "url": "https://9bits.com",
        "email": PUBLISHER["support_email"]}
    website = {"@type": "WebSite", "@id": ORIGIN + "/#website", "url": ORIGIN + "/",
        "name": "elo.now", "inLanguage": "en", "publisher": {"@id": ORIGIN + "/#publisher"}}
    page = {"@type": "WebPage", "@id": canonical + "#page", "url": canonical,
        "name": title + " · elo.now", "description": description, "inLanguage": "en",
        "isPartOf": {"@id": ORIGIN + "/#website"}, "primaryImageOfPage": {"@type": "ImageObject", "url": SOCIAL_IMAGE}}
    graph = [organization, website, page]
    if not legal:
        graph.append({"@type": "SoftwareApplication", "@id": ORIGIN + "/#app", "name": "elo.now",
            "url": ORIGIN + "/", "applicationCategory": "CommunicationApplication",
            "operatingSystem": "iOS, Android, macOS, Windows, Linux", "description": description,
            "publisher": {"@id": ORIGIN + "/#publisher"},
            "license": ORIGIN + "/LICENSE.txt", "isAccessibleForFree": True,
            "sameAs": ["https://github.com/elo-now/elo-now"]})
    # Inert JSON-LD, never interpolated JavaScript. Escape script-closing characters.
    return json.dumps({"@context": "https://schema.org", "@graph": graph}, ensure_ascii=False).replace("<", "\\u003c")


def shell(title, description, body, prefix="./", theme="light", legal=False, path="/"):
    canonical = ORIGIN + path
    schema = structured_data(title, description, canonical, legal)
    return f'''<!doctype html>
<html lang="en" data-theme="{theme}">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="{'#15231d' if theme == 'dark' else '#f7f9f6'}">
  <meta name="description" content="{esc(description)}">
  <meta name="robots" content="index, follow, max-image-preview:large">
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="elo.now">
  <meta property="og:locale" content="en_US">
  <meta property="og:title" content="{esc(title)} · elo.now">
  <meta property="og:description" content="{esc(description)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{SOCIAL_IMAGE}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="elo.now — private team communication">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{esc(title)} · elo.now">
  <meta name="twitter:description" content="{esc(description)}">
  <meta name="twitter:image" content="{SOCIAL_IMAGE}">
  <meta name="twitter:image:alt" content="elo.now — private team communication">
  <script type="application/ld+json">{schema}</script>
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; media-src 'self'; font-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'self'; form-action 'none'">
  <meta name="referrer" content="no-referrer">
  <title>{esc(title)} · elo.now</title>
  <link rel="icon" href="{prefix}favicon.svg" type="image/svg+xml">
  <link rel="preload" href="{prefix}fonts/Manrope-Variable.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="{prefix}style.css">
  <script src="{prefix}pronunciation.js" defer></script>
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<div class="page-shell">
<header class="site-header">
  <div class="header-brand">
    <a href="{prefix}index.html" aria-label="elo.now home">{brand("brand-lockup")}</a>
    <div class="brand-pronunciation" hidden>
      <button type="button" class="pronunciation-button" aria-label="Hear how to say elo" aria-describedby="pronunciation-status">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="m11 5-6 4H2v6h3l6 4V5Z"/><path d="M15 8a6 6 0 0 1 0 8M18 5a10 10 0 0 1 0 14"/></svg>
        <span>EH-loh</span>
      </button>
      <audio src="{prefix}assets/elo.mp3" preload="none" hidden></audio>
      <span id="pronunciation-status" class="pronunciation-status" role="status" data-error="Couldn’t play the recording. Tap to try again."></span>
    </div>
  </div>
  <nav aria-label="Main navigation"><a href="{prefix}index.html#product">Product</a><a href="{prefix}index.html#spaces">Spaces</a><a href="{prefix}index.html#privacy">Privacy</a><a href="{prefix}index.html#managed-hosting">For business</a><a href="{prefix}support/index.html">Support</a><a href="https://github.com/elo-now/elo-now" target="_blank" rel="noopener noreferrer">GitHub</a></nav>
  <div class="theme-switch" aria-label="Website color theme"><a href="{prefix}index.html"{' aria-current="page"' if theme == 'light' and not legal else ''}>Light</a><a href="{prefix}dark/index.html"{' aria-current="page"' if theme == 'dark' and not legal else ''}>Dark</a></div>
</header>
<main id="main">{body}</main>
<footer class="site-footer">
  <div>{brand("brand-footer")}<p>Private team communication. On your terms.</p><p>{contact()}</p></div>
  <nav aria-label="Legal and support"><a href="{prefix}support/index.html">Support</a><a href="{prefix}privacy/index.html">Privacy</a><a href="{prefix}terms/index.html">Terms</a><a href="{prefix}delete-account/index.html">Account &amp; data deletion</a><a href="{prefix}community/index.html">Community standards</a><a href="{prefix}LICENSE.txt">Open-source license</a></nav>
</footer>
</div></body></html>'''


def homepage(prefix):
    return f'''
<section class="hero" aria-labelledby="hero-title">
  <div class="hero-copy"><p class="eyebrow">OPEN-SOURCE COMMUNICATION FOR TEAMS</p>
  <h1 id="hero-title">Private team<br>communication.<br><span>On your terms.</span></h1>
  <p class="hero-intro">Bring conversations, files and live sessions together in Spaces. With encrypted messages, apps for your phone and desktop, and deployment on your own infrastructure.</p>
  <p class="encryption-note"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg><span>Messages encrypted on your device.</span></p>
  <div class="hero-actions"><a class="button" href="#download">Get elo.now <span aria-hidden="true">↓</span></a><a class="text-link" href="#managed-hosting">Let 9bits set it up</a></div>
  </div>
  <div class="hero-visual"><span class="orbit orbit-one" aria-hidden="true"></span><span class="orbit orbit-two" aria-hidden="true"></span><img class="hero-phone" src="{prefix}assets/product-chat.png" alt="A team coordinating a release in the Launch day conversation" width="402" height="874" fetchpriority="high"></div>
</section>
<section class="intro-band"><p class="eyebrow">A PLACE FOR YOUR TEAM’S WORK</p><h2>Keep the conversation.<br>Keep the context.</h2><p>For product teams, developers and organizations that want a say in how their communication runs. Discuss a project, share a file or join a live session in the same Space.</p></section>
<section class="private-deployment" id="managed-hosting" aria-labelledby="deployment-title"><div><h2 id="deployment-title">Your team’s workspace.<br>We’ll take care of it.</h2><p>Get a private elo workspace, ready for your team. 9bits handles installation and configuration on your own infrastructure, or hosts and manages it for you.</p><ul class="deployment-services"><li><strong>Set up for your organization.</strong> Spaces, access and storage configured around the way your team works.</li><li><strong>Hosted by us or on your infrastructure.</strong> Choose the option that fits your business.</li><li><strong>Ongoing care.</strong> Updates, monitoring, backups and support from the team behind elo.</li></ul></div><div class="deployment-contact"><h3>Let’s set up your team.</h3><p>Tell us about your organization. We’ll help you choose the right setup and prepare an offer.</p><a class="button" href="mailto:{esc(PUBLISHER["deployment_email"])}">Talk to 9bits <span aria-hidden="true">→</span></a></div></section>
<section class="product-section" id="product"><div class="product-copy"><p class="section-number">01 / CONVERSATIONS</p><h2>From a quick question<br>to a shared decision.</h2><p>Give a topic its own chat, talk directly with a teammate, and reply without losing the thread. Keep useful information within reach with search, pins and reminders.</p><ul class="feature-list"><li>General, topic chats and direct conversations</li><li>Replies, reactions, pins and search</li><li>Encrypted photos and files</li><li>Edit messages, mention teammates and keep local drafts</li><li>Fast message sync across your devices</li></ul></div><div class="product-image mint-panel"><img src="{prefix}assets/product-messages.png" alt="Team conversations in Studio North, with General and project chats" width="402" height="874" loading="lazy"></div></section>
<section class="product-section reverse"><div class="product-copy"><p class="section-number">02 / YOUR ATTENTION</p><h2>Catch up.<br>Get back to work.</h2><p>Buzz gathers unread messages. Mute conversations that can wait and set reminders for the ones that need your attention later.</p><ul class="feature-list"><li>Unread activity across your conversations</li><li>Optional notifications with links to the relevant chat</li><li>Muted conversations stay out of Buzz and message alerts</li><li>All, Mentions and Threads filters</li><li>Read state shared between your approved devices</li></ul></div><div class="product-image rose-panel"><img src="{prefix}assets/product-buzz.png" alt="Buzz showing unread team conversations and activity filters" width="402" height="874" loading="lazy"></div></section>
<section class="space-feature" id="spaces"><div><p class="section-number">03 / SPACES</p><h2>One profile.<br><span>Separate Spaces.</span></h2><p>A Space for your company, another for a project team. Each has its own members, General channel and conversations. Join with an invitation link or QR; owners can require approval.</p><p>Keep projects separate and choose who takes part in each conversation.</p><a class="text-link" href="{prefix}support/index.html#own-space">Plan your own deployment</a></div><img src="{prefix}assets/product-spaces.png" alt="Separate Spaces for fictional organizations, with Studio North selected" width="402" height="874" loading="lazy"></section>
<section class="details-grid" aria-label="More ways to work together"><article><p class="eyebrow">LIVE SESSIONS</p><h3>Talk it through.</h3><p>Voice and video bring the conversation beyond text. Start or join a live session from a chat, with full-screen video and screen sharing on desktop.</p></article><article><p class="eyebrow">YOUR DEVICES</p><h3>Keep access in view.</h3><p>Link your phone and desktop, manage device access and unlock with supported biometrics. Save recovery material for your identity and encrypted backups for your conversations.</p></article><article><p class="eyebrow">YOUR WORKSPACE</p><h3>Make room to focus.</h3><p>Adjust appearance and interface size. Use desktop shortcuts, paste images or drag files into a chat, and choose a notification sound or silence.</p></article></section>
<section class="architecture-section" id="architecture" aria-labelledby="architecture-title"><p class="eyebrow">HOW DATA MOVES</p><h2 id="architecture-title">Content stays encrypted<br>between your devices.</h2><p class="section-intro">Messages are encrypted on your device, delivered through your team’s server and decrypted on participants’ devices.</p>
<figure class="data-flow"><figcaption>Message delivery</figcaption><ol><li><span class="flow-step">01</span><h3>Your device</h3><p>Signs and encrypts the message for authorized recipients.</p></li><li><span class="flow-step">02</span><h3>Delivery server</h3><p>Stores ciphertext and delivery metadata under the Space’s retention policy.</p></li><li><span class="flow-step">03</span><h3>Their devices</h3><p>Verify the message and decrypt it with participant keys.</p></li></ol></figure>
<div class="architecture-notes"><article><h3>An independent check on access.</h3><p>A separate witness verifies signed access permissions for General channels, keeping authorization independent from message delivery.</p></article><article><h3>Built for live collaboration.</h3><p>Direct connections and media relays support voice and video sessions. Push notifications bring your attention back to new activity.</p><a class="text-link" href="https://github.com/elo-now/elo-now#how-data-moves">See how elo works on GitHub</a></article></div></section>
<section class="storage-feature" aria-labelledby="storage-title"><div><h2 id="storage-title">Your files.<br>Your storage choice.</h2><p>Space owners can connect a dedicated MEGA folder or S3-compatible storage, or choose a private hosting with storage already provided.</p><p>Photos and files are encrypted on your device before upload, with content keys shared with authorized conversation participants.</p></div><div class="storage-steps"><h3>Connect your storage</h3><dl><dt>MEGA</dt><dd>A dedicated folder link and its write access key. No account password.</dd><dt>S3-compatible</dt><dd>Your endpoint, bucket and restricted access credentials.</dd><dt>Changing storage</dt><dd>New uploads use the new location. Existing files keep their original expiry deadline.</dd></dl></div></section>
<section class="privacy-feature" id="privacy" aria-labelledby="privacy-title"><p class="eyebrow">PRIVATE BY DESIGN</p><h2 id="privacy-title">Your conversations.<br><span>Your control.</span></h2><p class="privacy-lead">Message and file content is encrypted for authorized participants. Delivery and storage services do not need the participants’ content decryption keys.</p><div class="privacy-columns"><div><h3>Open source.</h3><p>Inspect the code, adapt it to your needs and run it on infrastructure you choose.</p></div><div><h3>No AI integrations.</h3><p>elo does not send your conversation content to AI services.</p></div><div><h3>Your infrastructure.</h3><p>Run elo on your own servers or choose hosting managed by 9bits for your team.</p></div></div><a class="text-link" href="{prefix}privacy/index.html">Read our privacy policy</a></section>
<section class="retention-section" aria-labelledby="retention-title"><p class="eyebrow">RETENTION IS A CHOICE</p><h2 id="retention-title">Choose what stays.<br>And for how long.</h2><p class="section-intro">Set separate lifetimes for server delivery copies, individual messages and attachment downloads.</p><div class="retention-grid"><article><h3>Server copies</h3><p class="retention-value">6 / 12 / 24 h</p><p>Public elo.now offers up to 24 hours. Private hosting can also offer 48 hours or No expiry. Received history can stay on members’ devices.</p></article><article><h3>Keep a message</h3><p class="retention-value">No expiry / 1 / 24 h</p><p>Use Keep to choose an expiry time for each message, or leave it without a deadline.</p></article><article><h3>Attachment downloads</h3><p class="retention-value">1 / 12 / 24 h</p><p>Set how long new attachments remain available to download. One hour by default, with a choice of 12 or 24 hours.</p></article></div><a class="text-link" href="{prefix}terms/index.html">Read more in our terms</a></section>
<section class="faq"><p class="eyebrow">BEFORE YOU GET STARTED</p><h2>A few practical questions.</h2><details><summary>Who is elo for?</summary><p>Product teams, developers and organizations that want conversations, files and live sessions in one private workspace, with open source and a choice of hosting.</p></details><details><summary>Can I host it for my organization?</summary><p>Yes. Deploy elo on your infrastructure, or let 9bits handle installation, hosting and ongoing care for your team.</p></details><details><summary>Can server administrators read our messages?</summary><p>In current owner-managed Spaces, messages and attachments are encrypted for authorized conversation participants. Delivery and storage services handle encrypted content without receiving participants’ content-decryption keys. See our privacy policy and source documentation for the full architecture.</p></details><details><summary>Do new members see earlier messages?</summary><p>New members join General from the point they are admitted. Earlier conversation history stays separate from the invitation.</p></details><details><summary>Does an expired server copy delete my local history?</summary><p>No. The Space’s server lifetime controls delivery copies, while received history can stay on devices. Keep lets you set a separate expiry for individual messages.</p></details></section>
<section class="closing" id="download" aria-labelledby="download-title"><p class="eyebrow">ONE TEAM. PHONE AND DESKTOP.</p><h2 id="download-title">Get elo.now.</h2><p>Choose your platform and check its release notes.</p>{download_links()}<p class="release-note">Store availability depends on platform approval and region.</p><a class="text-link" href="{prefix}support/index.html">Setup and support</a></section>
'''


def download_links():
    links = []
    for key, label in [("app_store_url", "Download on the App Store"), ("google_play_url", "Get it on Google Play")]:
        url = PUBLISHER.get(key)
        if url:
            if not url.startswith("https://"):
                raise ValueError("Store URLs must use HTTPS")
            links.append(f'<a class="button" href="{esc(url)}">{label}</a>')
    mobile = '<div class="download-links">' + ''.join(links) + '</div>'
    release = PUBLISHER.get("desktop_release_url", "https://github.com/elo-now/elo-now/releases")
    if not release.startswith("https://github.com/"):
        raise ValueError("Desktop release must use GitHub HTTPS")
    desktop = f'<div class="download-links desktop-downloads"><a class="button" href="{esc(release)}">Download for desktop<span class="download-caption">macOS · Windows · Linux</span></a></div>'
    return mobile + desktop


LEGAL = {
"privacy": ("Privacy policy", "How elo.now handles encrypted communication, operational metadata and your chosen storage.", f'''
<p class="lead">elo.now is a platform for team communication built around locally held identities and separate Spaces. Message and attachment content is encrypted, but running the service still requires processing personal data and operational metadata. This policy explains that distinction.</p>
<h2>Who is responsible?</h2>{company()}<p>Privacy contact: {contact("privacy")}. This publisher is responsible for this website and services it operates. A company or other organization operating a Space is responsible for its own purposes and processing; hosting and service-provider responsibilities depend on the actual arrangement. Ask that organization for its privacy information. Using the same app does not make every Space part of the same organization.</p>
<h2>Which service are you using?</h2><p>Available features and providers depend on your app version and the service configured for each Space. Installing an update does not move existing Spaces to a different server. The newer deployment supports a separate authorization witness and owner-configured attachment storage. Supported versions also let you import an independent operator’s signed hosting configuration and select it for a new Space. That configuration identifies public service endpoints, verification keys and available policies; it does not contain provider storage credentials. Import it only from an administrator you trust. Older Spaces may still use publisher-configured MEGA storage and require an owner device to be online for admission. Independent operators choose their own infrastructure and must explain their processing separately.</p>
<p>Earlier version-1 hosted General used an enrollment-service reader credential. Existing Spaces on that legacy implementation can therefore expose General content to their operator; updating the app alone does not revoke those keys. Current owner-managed Spaces keep General decryption keys on participant devices.</p>
<h2>Your profile and device</h2><p>You choose a name and create a local cryptographic identity. Profile information, contacts, conversation history, preferences and cryptographic material are held on your device. The local password protects your saved profile. Optional biometric unlocking uses the operating system; elo does not receive your face or fingerprint template.</p><p>Your public identity, device credential and chosen profile information are shared where needed to identify you to conversation participants and Space services. Do not send your password, recovery words or recovery QR to support.</p>
<h2>Messages and Spaces</h2><p>Messages are encrypted on the sending device before transmission to storage services called Replicas. Authorized participants decrypt them on their devices. A Space groups membership, General and other conversations; joining a Space does not automatically grant access to every private chat or to earlier General history. Service signing and transport keys are not participant keys for decrypting message content.</p><p>Encryption does not prevent an authorized participant from saving, exporting or sharing received content, including sending it to an external AI service. A compromised participant device can expose readable content. The current app has no integration that submits conversations to an AI service on the publisher’s behalf. These limits are different from whether an infrastructure operator holds content-decryption keys.</p>
<h2>Data processed by our services</h2><p>Publisher-operated services process the following data, including where message content is encrypted:</p><ul>
<li><strong>Network information:</strong> IP addresses are visible during connections and may appear in error and security logs. Address or network hashes and request counters help limit abuse. A hash is not a guarantee of anonymity.</li>
<li><strong>Delivery metadata:</strong> object and route identifiers, sizes, storage times, queue state and delivery attempts support synchronization, retries and storage limits. A storage receipt does not prove that a person received or read a message.</li>
<li><strong>Notification identifiers:</strong> Firebase installation or registration identifiers, account bindings, delivery routes, preferences and unread-attention state support push delivery, muting, badges and removal of registrations.</li>
<li><strong>Membership and access information:</strong> public profile identifiers, chosen names, Space membership, roles, invitations, join requests and access decisions let services check permissions.</li>
<li><strong>Device information:</strong> public device identifiers and keys, signed credentials and their association with a profile and its permissions support device approval, revocation and recovery. These are not your private signing keys.</li>
<li><strong>Storage configuration:</strong> where the owner enables attachments, the storage broker processes the chosen provider, restricted storage credentials, object identifiers, sizes, deadlines and transfer state.</li>
</ul><p>An optional introduction note in a signed join request is visible to the approval service and owner. It is removed from the queue’s stored applicant record after a decision; replay responses may retain it for up to two minutes. A hosted Space’s primary owner supplies a contact email for membership and data requests. Current members can see it; it is replaced when a new primary owner accepts the role with a replacement address. Creating a profile or joining as a member does not require an email address.</p>
<h2>Authorization witness and invitations</h2><p>On deployments that support it, a separately configured witness validates and records covered authorization changes against owner-signed policies. An eligible open invitation can be used while the owner is offline; approval-required invitations still require the owner’s decision. The witness processes public authority proofs, invitation policies, device and membership identifiers, counters and signed receipts. It is not a message-content store and does not need message-decryption keys.</p><p>A shortened Space invitation can reference an encrypted descriptor on the API. The invitation’s decryption material remains in the shared link, not in that stored descriptor. Whoever receives a usable open invitation may use it within its policy and validity period. Share links only with intended recipients; owner approval provides an additional access decision. The self-contained My code contact card is read from the code itself and is not stored as a server-hosted contact card by this feature.</p><p>The witness and API have separate service keys and access controls. This separation does not guarantee protection against compromise of participants, both services or their shared infrastructure administration. In the publisher’s newer deployment, the witness and storage broker run as separate services on the same host; a compromise of that host could affect both roles.</p>
<h2>Attachments and storage providers</h2><p>Files are encrypted on your device before upload. Authorized participants receive the file-decryption key inside an encrypted message and can decrypt and save the file. Attachment bytes are not included in conversation backups.</p><p>Where owner-configured storage is available, the Space owner enables attachments during creation or in Space settings and connects a dedicated MEGA folder using its folder link and write key, or an S3-compatible bucket using restricted credentials. MEGA is a third-party cloud service; an owner’s account is not a server physically controlled by that owner. A hosting operator may instead offer managed attachment storage, with provider credentials configured on its storage broker. The app requests this configuration during Space creation without asking the owner to enter provider credentials.</p><p>Provider credentials are sent to and retained by the separate storage broker, which uses them to upload, retrieve and delete encrypted objects. The API does not receive those storage credentials in this flow. The broker can use them and is therefore a trusted holder of storage access, even though it does not receive the file-decryption keys. The provider sees the account or bucket, encrypted objects and transfer metadata. Disabling storage stops new uploads; existing files remain downloadable until their own deadlines. Changing provider applies to new uploads, while existing objects retain their original provider and deadline. Credentials for an older configuration remain while retained objects need them, including for deletion; they become eligible for removal once no object or active configuration needs them. Revoking those credentials at the provider can prevent downloads and cleanup.</p><p>Older publisher-operated Spaces may use MEGA configured by the publisher. They do not automatically acquire owner-configured storage after an app update. Applicable file-size, quota and expiry limits are shown by the app or service.</p>

<h2>Optional system notifications</h2><p>When you enable system notifications, elo uses Google Firebase Cloud Messaging and, on Apple devices, Apple Push Notification service. These providers process installation or registration identifiers and delivery information. elo’s notification service stores the device registration and opaque routing, preference and unread-attention information needed to deliver and quiet alerts. A signed public account identifier links registrations from the same account so they can be deleted together.</p><p>Notification routing targets are encrypted. Message text and conversation names are not included in the current generic system notification payload. You can disable system notifications in Settings or mute a conversation. OS settings may also control delivery.</p><p>See <a href="https://firebase.google.com/support/privacy/">Firebase’s privacy information</a> and <a href="https://www.apple.com/legal/privacy/">Apple’s privacy policy</a>. Their processing and international transfers must be considered alongside those of your Space operator.</p>
<h2>Live updates and activity indicators</h2><p>An authenticated live connection signals available updates. Typing, foreground online status and attachment-upload indicators are signed and encrypted for conversation participants. They expire and are not added to message history or sent as system notifications. The server still observes connection addresses, timing, routing and traffic sizes.</p>
<h2>App updates</h2><p>Versions with update checking request a public release policy when the app starts, without sending a profile identifier or device credential. The server receives ordinary network information such as the IP address. The policy is cached locally and may require an update through an official download page.</p>
<h2>Permissions</h2><p>Camera access is used when you choose to scan a QR, take a photo or video, set a profile photo, or enable video in a chat session. Microphone access is used when you choose to start or join an audio session in a chat. Desktop screen recording is used only when you choose to share your screen. File and photo access supports the files or images you choose to open, share or save. System notifications and biometric unlocking are optional. Refusing an optional permission does not stop you using the rest of the app.</p>
<h2>Live chat sessions</h2><p>You choose to start or join an audio session from an open chat. Camera and desktop screen sharing are enabled separately at your choice. On supported mobile devices, audio may continue when you switch apps or lock the screen until you leave the session or sign out; Android displays an ongoing session notification. Operating-system restrictions, permissions and connectivity can interrupt a session.</p><p>Live chat sessions use a separate service for signaling and media delivery. Other participants can see your chosen name and media you enable during the session. Session services and network providers process connection metadata, including network addresses, timing and participation. On compatible networks, media may travel directly between participants; relays can carry media when a direct connection is unavailable. The app does not record sessions for the publisher.</p>
<h2>Backups and recovery</h2><p>Recovery codes restore your identity; they are not a copy of chat history. Exported encrypted backups include supported profile and conversation data, but not attachment bytes. The backup budget is 64 MiB before encryption and compression; older message groups may be omitted to fit. The app reports omissions. You control where an exported backup or recovery QR is saved and shared.</p>
<h2>Website, support and diagnostics</h2><p>This static website uses locally hosted fonts and images. Its supplied code has no advertising, analytics scripts or tracking cookies. The web host may process normal request and security logs. If you contact support, the provider receives the contact information and material you choose to send. Avoid including unnecessary conversation content or secrets.</p><p>The app does not include advertising or an analytics dashboard. Optional diagnostic information shown by the app is not automatically a support submission.</p>
<h2>Automatic account deletion</h2><p>Encrypted content carries signed public attribution identifying its publishing account and, for shared contact or history bundles, the accounts represented in the bundle. This lets the service remove the appropriate ciphertext without reading message text. The service keeps a minimal deletion marker and authority/revocation proofs to prevent removed access or content being restored. See the <a href="../delete-account/index.html">account deletion instructions</a> for the in-app action and retained-copy limitations.</p>
<h2>Why data is processed</h2><p>For publisher-operated services, processing necessary to provide the communication, membership and support services you request is based on performance of the applicable service contract (GDPR Article 6(1)(b)). Protecting accounts and infrastructure, limiting abuse and investigating security incidents serves our legitimate interests and those of users (Article 6(1)(f)). Where a law requires retention or disclosure, the basis is the relevant legal obligation (Article 6(1)(c)). Where optional processing requires consent, consent is requested and may be withdrawn (Article 6(1)(a)); an operating-system permission is not by itself a description of every legal basis.</p><p>An organization using elo for work must identify its own purposes and lawful bases, inform its users and arrange any required processing agreements. Installing open-source software does not, by itself, establish compliance or make the publisher that organization’s processor for every purpose.</p>
<h2>Personal blocking</h2><p>Blocking is a private preference for your profile on this device, across its Spaces. Blocked users’ messages and reactions are hidden, and their personal requests are dismissed. The notification service verifies the sending device’s signed identity proof and checks a recipient-owned block list; it sees sender identity during verification but not message plaintext. It stores a route-specific sender tag for policy and queued delivery. The block list is included in encrypted backups and can be managed in More → Blocked users. Other devices require their own updated preferences. Blocking does not revoke another member’s access to messages in a shared channel.</p>
<h2>Three different expiry settings</h2><ul>
<li><strong>Server message lifetime:</strong> public elo.now hosting offers 6, 12 or 24 hours, with 24 hours selected by default. An imported private hosting profile can offer additional choices, including 48 hours or No expiry. The owner selects from that host’s available policies when creating the Space. A finite lifetime bounds availability of encrypted message bodies in server delivery storage; copies can be removed earlier, including after an accepting device acknowledges direct-message delivery. With No expiry, bodies and their encrypted locators have no automatic deadline and remain after that acknowledgement. Neither policy guarantees availability or unlimited capacity: quotas, explicit deletion and the operator’s storage and backup policies still apply. A server policy does not erase received history on every device. Copies that reach a finite deadline become unavailable for normal download and enter cleanup.</li>
<li><strong>Keep — No expiry, 1 hour or 24 hours; default No expiry:</strong> this separate, optional message setting controls expiry of message content in participating elo apps. In the composer, ∞ means No expiry. After a timed deadline, the app removes the content and shows Message expired when it processes expiry. Older versions may call this setting Delete after or retain other previously supported deadlines. Keep: No expiry does not change the Space’s server policy or guarantee permanent availability; server No expiry does not disable a message’s Keep deadline.</li>
<li><strong>Attachment expiry — 1, 12 or 24 hours; default 1 hour:</strong> the Space owner selects the download lifetime for new uploads. The deadline starts at upload reservation. Changing this setting does not rewrite earlier files’ deadlines. At expiry, new downloads are blocked and encrypted objects enter deletion at the storage provider. Provider or service failures can delay physical cleanup.</li>
</ul><p>If you remain offline beyond the server delivery period, missing history may require another authorized participant with a retained copy to reconnect and synchronize. Retrieval is not guaranteed. Received history and cached attachments can remain after server expiry. Message expiry cannot erase screenshots, exports, files saved independently or copies outside elo, and cannot make an offline device process changes immediately.</p>
<h2>Retention of other data</h2><p>The settings above do not define the lifetime of all metadata, logs or backups. The current services use these separate periods and criteria:</p><ul>
<li><strong>Push delivery:</strong> ordinary queued targets and duplicate-prevention records expire within 24 hours. Session-start hints expire within 60 seconds. Device routes expire after 30 days without renewal; preference and unread-attention records are associated with the route and may remain until read, updated, removed or the route is cleaned up. Deletion and housekeeping remove eligible records. Firebase and Apple apply their own retention independently.</li>
<li><strong>Membership, devices and permissions:</strong> current records remain while needed to operate a Space and determine access. Account or Space deletion removes supported membership and contact data. Minimal signed authority, revocation, receipt and deletion records may remain to reject replay or restoration of removed access; these safeguards do not have a message-style automatic expiry.</li>
<li><strong>Invitations:</strong> encrypted short-link descriptors are eligible for cleanup at their stored expiry. Expiry or revocation prevents new admission, but does not erase authority history or an existing participant’s membership. Self-contained contact codes do not create a hosted contact-card record.</li>
<li><strong>Abuse controls:</strong> daily request budgets reset or are pruned as the day changes. A network hash associated with Space creation can remain with that Space’s allocation record so active-Space limits survive restarts and daily resets. These hashes are not covered by the message expiry setting.</li>
<li><strong>Storage access:</strong> object records and the credentials needed to reach their provider remain through expiry and successful cleanup. Retired provider credentials are eligible for removal once neither an active configuration nor any retained object requires them. Failed provider deletion keeps the cleanup record and can prolong this period.</li>
<li><strong>Operational backups:</strong> encrypted recovery snapshots are separate from live delivery storage. Server staging rotation and independently retained recovery copies have separate lifecycles. A message or attachment deadline does not erase every snapshot. Independently pulled backups are not automatically purged by the server’s expiry job; their removal requires operator action based on recovery needs, pending deletion requests and applicable retention duties.</li>
<li><strong>Logs and support:</strong> host and service logs follow separate rotation settings; incident evidence and support correspondence may be retained while needed to resolve a request, investigate an incident, meet a legal duty or address a claim. Their expiry is not controlled by a Space. Contact the publisher for the schedule and records applicable to your deployment.</li>
</ul><p>Disconnecting a Space removes that Space’s local conversations and contacts from that device. Removing a local profile removes its local data. Neither action erases independent copies on other devices, exported backups or every server. See <a href="../delete-account/index.html">account and data deletion</a> for the distinct server-side deletion action and retained-copy limitations.</p>
<h2>Your choices and rights</h2><p>Depending on applicable law, you may request access, correction, deletion, restriction or portability of personal data, object to certain processing, or withdraw consent. Contact {contact("privacy")} for publisher-operated services, or the administrator of the relevant company Space. You may also complain to your competent data protection authority. Requests must be verified proportionately; we will not ask for your recovery secret.</p>
<h2>Recipients and international processing</h2><p>Authorized participants receive the content you share with them. Space operators and authorized service administrators process the operational data described above. Publisher-operated infrastructure uses OVHcloud hosting; optional notifications use Google Firebase and Apple. Attachments use MEGA or the S3-compatible provider configured for the relevant Space and version. S3 compatibility does not necessarily mean Amazon operates that storage. Hosting, storage, notification and support providers process data needed for their respective services; competent authorities may receive information where lawfully required.</p><p>The newer publisher deployment uses servers in the European Union; older Spaces can remain on earlier infrastructure outside the EU. Notification providers and owner-selected storage can process data in other countries. A server’s location alone is not a promise that all processing stays in that country. Contact {contact("privacy")} for the provider arrangements, locations and applicable transfer safeguards for the service you use; independent Space operators must provide their own information. See <a href="https://firebase.google.com/support/privacy/">Firebase’s privacy information</a> and <a href="https://www.apple.com/legal/privacy/">Apple’s privacy policy</a>.</p>
<h2>Changes</h2><p>This policy will be updated when the product or processing changes; material changes will be communicated as required. A preview build, free service or testing arrangement does not remove applicable data-protection rights.</p>
'''),
"terms": ("Terms of use", "Terms for using elo.now and publisher-operated Spaces.", f'''
<p class="lead">elo.now brings team conversations, shared files and live audio/video sessions together in separate Spaces. These terms describe responsible use and the boundaries of a service built around participant-controlled identities.</p>
<h2>Provider and scope</h2>{company()}<p>Contact: {contact()}. These terms cover services operated by the named publisher. An independently operated company Space may have additional terms supplied by its operator. Nothing here limits rights granted under applicable open-source licenses or mandatory consumer law.</p>
<h2>Your profile</h2><p>Use a name and content you are entitled to use. Protect your device, local password and recovery code. Anyone who obtains your recovery material may be able to act as you. The provider cannot reset your cryptographic identity from an email address or recover secrets it does not hold.</p><p>Use the app only if you can agree to these terms under the law that applies to you, or with the appropriate authorization of a parent, guardian or organization. The service is not designed as a children’s service.</p>
<h2>Joining and leaving Spaces</h2><p>A Space invitation may expire, be revoked or require owner approval. Treat an open invitation as access material: anyone who receives a usable link may be able to join under its policy. On services that support witnessed admission, eligible open invitations can work without an owner device online; other flows still require an owner’s action. Joining General gives access to future conversation; it does not automatically grant earlier history or access to every private conversation in the Space. Owners and organization administrators are responsible for choosing membership policies and who may join.</p><p>Disconnecting a Space stops local synchronization and removes its local data from that device. It is not a promise that content disappears from other participants’ devices or backups. Ask the operator about revoking server-side membership and deleting operator-held information.</p>
<h2>Your content</h2><p>You retain the rights you have in your messages and files. You authorize the processing needed to deliver, store and display them to the recipients you choose. Only share content you are permitted to share, and respect the confidentiality and rights of others.</p>
<h2>Acceptable use</h2><p>Do not use elo for unlawful activity, child sexual abuse or exploitation, threats, harassment, hate directed at protected groups, fraud, impersonation, non-consensual intimate imagery, intellectual-property infringement, spam or distribution of malware. Do not attempt unauthorized access or deliberately disrupt another person’s Space or infrastructure. See our <a href="../community/index.html">community standards</a>.</p><p>Report concerns to your Space administrator or {contact()}. The relevant operator may investigate, restrict access or preserve information when necessary to protect users or comply with law. You may report concerns to elonow@9bits.com; include only the information needed to investigate your report.</p>
<h2>Availability and backups</h2><p>Delivery depends on network access, recipients’ devices, configured servers and operating-system notification policies. elo is not an emergency communication service. Spaces, conversations, messages and attachments can be removed by authorized user actions, account or Space deletion, retention rules, storage limits or technical failures. Deleted or unavailable content may not be recoverable. Save recovery material and, where needed, encrypted conversation backups. A recovery code alone does not restore history. Exported backups exclude attachment bytes and may omit older messages to stay within the displayed size budget; keep separate copies of files you need to retain.</p>
<h2>Message and attachment availability</h2><p>Public elo.now hosting offers Server message lifetime choices of 6, 12 or 24 hours, with 24 hours selected by default. Imported private hosting profiles can offer additional policies, including 48 hours or No expiry. The owner selects an available policy when creating the Space. A finite lifetime is the maximum delivery-storage period for encrypted message bodies, not guaranteed minimum availability. Copies may be removed earlier, including after an accepting device acknowledges direct-message delivery. Server No expiry retains encrypted bodies and locators without an automatic deadline, including after that acknowledgement; it does not disable quotas, explicit deletion or the operator’s storage and backup policies, or guarantee permanent availability. Received messages can remain on members’ devices after a server copy expires. Missing history may then depend on another authorized participant reconnecting with a retained copy; some messages may no longer be available.</p><p>The optional Keep setting is separate: No expiry, 1 hour or 24 hours, with No expiry selected by default and shown as ∞ in the composer. A timed setting controls when elo removes message content and shows Message expired in participating apps, including in a Space with server No expiry. Offline devices process expiry when the app runs again. Older versions may label this Delete after or retain a different previously supported deadline. Keep: No expiry does not change the Space’s server policy. Screenshots, exports and other independently retained copies cannot be recalled.</p><p>Attachments have their own download deadline, starting at upload reservation: 1 hour by default, with 12-hour and 24-hour options in Space settings for future uploads. Existing uploads keep their original deadline. New downloads stop at expiry; encrypted storage copies enter deletion, which can be delayed by provider or service failures. Already downloaded files can remain on participants’ devices. Save files you need before their displayed deadline; recovery codes and conversation backups do not restore attachment bytes.</p><p>These settings do not erase operational backups, access records, security logs or every independent copy at the same time. The <a href="../privacy/index.html">privacy policy</a> explains their separate retention and deletion criteria.</p>
<h2>Attachment storage configuration</h2><p>On supported versions and services, owner-configured attachments start disabled. A Space owner can enable them during creation or later in Space settings by connecting a dedicated MEGA folder with write access or an S3-compatible bucket with restricted credentials. The owner must have permission to use the storage, provide access scoped to the intended location and comply with the provider’s terms. The separate storage broker holds and uses these credentials to transfer and delete encrypted files; the app API does not receive them in this flow. The broker does not receive the file-decryption keys. A hosting operator may also offer managed storage with provider credentials configured on the broker. When the owner creates a Space on that hosting, the app requests managed storage without asking for provider credentials. The broker still verifies the owner’s authority and its allowed-owner policy. These credentials are not included in a hosting configuration QR or invitation link.</p><p>Changing storage applies to future uploads. Existing objects retain their original provider and expiry. Disabling attachments stops new uploads but does not immediately erase files that remain downloadable until their deadlines. Older credentials are retained while needed for existing objects and their cleanup. Removing access at the provider can prevent both download and deletion. Provider quotas, outages, account suspension and loss of credentials can make files unavailable. Older Spaces may instead use publisher-configured storage.</p>
<h2>Supported versions and updates</h2><p>Features described on the project website or in source documentation may be ahead of the version available in a particular store. Release notes and your app’s controls identify the features available to you. A newer app does not automatically migrate an existing Space’s server or storage. Preview builds are identified in their distribution channel; a preview label or a free service does not waive mandatory consumer or data-protection rights.</p><p>Security and compatibility updates may be necessary to keep using connected services. We may require an update after it is available through the official download channel for your platform, with notice and a reasonable opportunity to install it, subject to applicable law. Versions that support this check show the requirement and link to the download page; they do not silently install software or delete your profile. Availability can depend on the operating system, device and store region. If your device cannot install a required update, contact support about available options before removing the app or its data. This clause does not reduce statutory rights or obligations concerning updates, service changes or remedies.</p>
<h2>Pricing and third-party services</h2><p>The elo.now app and current publisher-operated hosting are free at launch. Published service limits currently include two Spaces per creator identity, 150 MB of encrypted message storage and 50 MB of separate encrypted attachment quota per Space, with individual files limited to 5 MB. Technical capacity and anti-abuse limits also apply; these figures do not promise unlimited availability or include a paid third-party storage plan. Any future paid offer will disclose its price and conditions before you agree to it. Your own hosting, attachment storage, network or platform provider may charge separately. Apple, Google, storage providers and independent Space operators apply their own terms.</p>

<h2>Ending use and data requests</h2><p>You may stop using the app, remove a local profile or delete your account through More → Legal → Delete account. The <a href="../delete-account/index.html">deletion page</a> explains automatic server cleanup, primary-owner requirements and the separate option to request deletion without the app. Legal duties and the rights of other participants may affect what can be erased.</p>
<h2>No warranties</h2><p><strong>To the maximum extent permitted by applicable law, elo.now and publisher-operated services are provided “as is” and “as available”, without contractual warranties, whether express or implied, including merchantability, fitness for a particular purpose, uninterrupted availability or freedom from errors.</strong> We do not guarantee that the app, encryption or hosting will be entirely secure, free from vulnerabilities, compatible with every device, or able to prevent unauthorized access, data loss or corruption. No software or encryption system can provide absolute security.</p>
<h2>Data and continuity</h2><p>You are responsible for protecting your devices, passwords and recovery material and for keeping and checking independent backups appropriate to your needs. Do not use elo.now as your only archive, emergency communication channel or a system whose failure could endanger life or health. Recovery codes alone do not restore conversation history. Backups omit attachment bytes and may omit older messages within the stated size budget. A Space owner or other authorized participant may remove a Space or content within their permissions; this may also remove access for other participants. The provider cannot promise to restore a deleted Space, conversation, message or attachment.</p>
<h2>Limitation of liability</h2><p><strong>For business users, to the maximum extent permitted by law, 9bits sp. z o.o. excludes liability for damage arising from use of, or inability to use, the app or services, including loss, deletion, corruption or disclosure of data; loss or deletion of Spaces, conversations, messages or attachments; security incidents; delayed, missing or duplicated communications; service interruption; lost profits, revenue, business opportunities or goodwill; and the cost of replacement services or data recovery, whether the damage is direct, indirect or consequential and whether or not its possibility was known.</strong> These exclusions also cover damage caused by independent hosting providers, other participants, third-party software and loss of recovery material, to the extent such liability can lawfully be excluded.</p><p>For consumers and persons entitled to equivalent statutory protection, these exclusions apply only to the extent permitted by the mandatory law that protects them. No clause excludes or limits liability for intentional misconduct, death or personal injury where liability cannot be excluded, mandatory consumer remedies, statutory data-protection rights or any other liability that cannot lawfully be excluded or limited. The free nature of the service does not remove those rights. If an exclusion is unenforceable, the applicable law governs that liability; the other provisions remain effective to the extent permitted by law.</p>
<h2>Complaints and applicable law</h2><p>Send service complaints to {contact()}. Polish law governs these terms, without depriving consumers of mandatory protections or competent courts available under the law of their habitual residence. Nothing requires consumers to waive access to a court or statutory complaint procedure.</p>
<h2>Changes</h2><p>The provider may update these terms when the service or applicable law changes. Material changes will be communicated as required. Open-source software license terms continue to apply independently.</p>
'''),
"support": ("Support", "Help with elo.now profiles, Spaces, notifications and recovery.", f'''
<p class="lead">A little help getting into the right conversation.</p><h2>Contact support</h2><p>{contact()}. Include your device model, operating-system version, app version and a short description of what happened. Never include your password, recovery words, recovery QR or private server credentials.</p>
<h2>Join a Space</h2><p>Open More → Spaces → Join a Space. Scan the invitation QR inside elo or paste its link. If approval is required, wait for the owner’s decision. Expired invitations need to be replaced by the owner.</p>
<h2 id="own-space">Set up your own Space</h2><p>Choose “Create a Space”, enter its name and a contact email for its primary owner, choose the available admission and message-lifetime settings, and share the invitation QR or link. The creator becomes its primary owner. Current elo hosting is free at launch and allows two Spaces per creator identity with 150 MB of encrypted message storage per Space and a separate 50 MB attachment quota. You can also connect to a Space prepared on an independent organization’s server.</p><p>In supported versions, choose Hosting when creating a Space. To use a private host, choose Add hosting, scan the administrator’s hosting QR or paste its link, review the public service details and add it. A private Space invitation may require this configuration to be added first. The hosting configuration carries public endpoints, verification keys and policies, not storage-provider credentials; get it from an administrator you trust.</p><p>Where supported, enable attachments during creation or in Space settings and connect a dedicated MEGA folder with a write key or an S3-compatible bucket with restricted credentials. The MEGA form does not ask for your account password. If the selected hosting offers managed storage, the app configures attachments during Space creation without asking for provider credentials; the operator configures those on its storage broker. Changing provider affects new uploads; existing files keep their original provider and expiry. Store releases and existing Spaces may offer a different storage model.</p><p>For deployment instructions, see the <a href="https://github.com/elo-now/elo-now">project documentation</a> or contact support. Keep server and storage credentials out of invitation messages and support requests. A QR invitation should carry the invitation link, not the administrator’s private configuration.</p>

<h2>Restore your profile</h2><p>From the sign-in menu, choose Recover. Use your recovery code or protected QR. If you also saved an encrypted backup, use the backup restore flow to bring supported history back. Your recovery code alone restores identity, not a complete archive of old conversations.</p>
<h2>Update the app</h2><p>Install updates from the <a href="https://apps.apple.com/app/id6814766127">App Store</a>, <a href="https://play.google.com/store/apps/details?id=now.elo">Google Play</a> or the <a href="https://github.com/elo-now/elo-now/releases">desktop releases page</a>. If elo shows “Update required to go online.”, open the appropriate store or release page yourself, install the current version and reopen the app. You can still use saved chats and local features while online actions are paused. If the update is not available for your device or region, contact support. Do not uninstall the app to retry: local history may be lost. Keep your recovery material and backups safe.</p>
<h2>Notifications</h2><p>Open More → Settings and enable System notifications in the Notifications section, then allow them in your operating system. A muted chat does not produce message notifications or Buzz entries. System Focus, battery and notification settings can affect delivery. Reading a conversation allows its next unread alert to make a sound again.</p>
<h2>Missing messages and expiry</h2><p>Public elo.now hosting offers a Server message lifetime of 6, 12 or 24 hours, with 24 hours selected by default. An imported private hosting profile can also offer 48 hours or No expiry; the Space uses the policy selected at creation. Server No expiry retains encrypted bodies and locators after direct-message acknowledgement but does not remove quotas or prevent explicit deletion. Received local history may remain longer than a finite server lifetime. If a delivery copy is no longer on the server, Retrieve can succeed only if an authorized device with the required copy becomes available and synchronizes. Ask another participant to open and unlock elo; recovery is not guaranteed. Keep controls a separate message-content deadline: its No expiry (∞) choice does not change the server policy. Attachments have a separate 1-, 12- or 24-hour deadline, starting at upload reservation; the default is 1 hour. Backups follow separate operator policies.</p>
<h2>Leave or remove data</h2><p>Use Spaces to disconnect a Space from this device. To delete your account, remove only a saved local profile or request deletion without the app, follow the <a href="../delete-account/index.html">account and data deletion instructions</a>.</p>
<h2>Report abuse or a security issue</h2><p>Contact your Space administrator or {contact()}. For a vulnerability, describe how to reproduce it using a test profile; do not include another person’s private data. For immediate danger, contact the appropriate emergency service.</p>
'''),
"delete-account": ("Account & data deletion", "Delete your elo.now account in the app or request deletion without reinstalling it.", f'''
<p class="lead">Account deletion, local profile removal and leaving a Space are different actions.</p>
<h2>Delete your account in the app</h2><p>Open the account you want to delete, then go to More → Legal → Delete account. Read the confirmation, enter your profile password and tap Delete account. No email is required. If you have no Spaces and see Create a Space / Join a Space, open Legal from the upper-right corner.</p><p>The app checks your current Spaces. Primary ownership stays with the profile that created the Space and cannot be transferred. If you are a primary owner, open More → Spaces and tap the settings icon for that Space. Remove any other members in Members, then use Details → Delete Space. This removes the Space for everyone; tell its members before doing so. Then return to Delete account.</p><p>Once the connected services accept the deletion request, the app removes saved profiles and app data for this account from this device and signs you out. Server cleanup runs automatically in the background; you do not have to keep the app open. The app retains only an opaque, read-only receipt and confirms completion when opened online. Temporary service failures can delay cleanup; accepted work retries automatically. If a service cannot be reached, the app keeps the local profile so you can retry. A request already accepted by another service continues even if a later step fails.</p><p>On supported services, deletion removes membership and application contact details, attributed message and file ciphertext, associated delivery work and push registrations. Dedicated server snapshots of affected Spaces are removed. Minimal signed authority and revocation records and a deletion marker remain to prevent deleted credentials or content being reintroduced.</p>
<h2>Request deletion without the app</h2><p>For services run by the elo.now publisher, contact {contact()} with the subject “elo.now account deletion request”. State which Space or service you used and the public Identity ID, if you have it. If you do not have that ID, describe your account so support can help identify a safe verification route. You do not need to reinstall the app.</p><p>Never send a password, recovery words, protected recovery QR or private key. Support verifies requests proportionately and explains any records that must be retained, why, and for how long.</p>
<h2>Data in a particular Space</h2><p>To contact a Space owner about particular data without deleting your whole account, select the Space and open More → Legal → Request data deletion. Use draft prepares text addressed to the current primary owner; you choose whether to send it. Each primary owner must maintain a working contact address and can update it in Space settings.</p>
<h2>Company-operated Spaces</h2><p>If another organization operates the service, its deletion endpoint and policies apply. The elo.now publisher cannot directly erase an independent operator’s infrastructure. Contact that operator if its service is unavailable or does not support automatic account deletion.</p>
<h2>Remove a local profile</h2><p>More → Recovery → Remove from this device removes only the selected local profile and its saved keys and history. Other accounts remain. Signing out or uninstalling alone does not request server-side account deletion.</p>
<h2>Disconnect one Space</h2><p>In More → Spaces, confirm Disconnect for that Space to remove its conversations and contacts from this device and stop synchronization. Your account and other Spaces remain.</p>
<h2>What can remain?</h2><p>Other participants and offline devices may retain previously received messages. Files or backups saved outside elo and copies held by independent parties cannot be remotely erased. Old backups do not restore revoked access to our services. Additional operator-held support or legally required records follow the privacy policy and applicable retention obligations; contact {contact()} about those records.</p>
'''),
"community": ("Community standards", "Responsible use and reporting for elo.now Spaces.", f'''
<p class="lead">A Space should be somewhere people can talk, plan and work together without harassment or abuse.</p><h2>What is not allowed</h2><p>Do not share child sexual abuse material, facilitate child exploitation or grooming, threaten people, encourage violence, harass or bully others, or promote hatred against protected groups. Non-consensual intimate imagery, impersonation, scams, malware, spam and unlawful content are prohibited. Respect intellectual property and other people’s confidential information.</p>
<h2>Block a user</h2><p>Use “Block user” from a message’s menu or Contacts to hide that person’s messages, reactions and direct requests on this device. Manage or undo blocks in More → Blocked users. Notification protection takes effect when the device confirms its updated policy with the notification service. Blocking does not remove a member from a shared Space; report abuse separately so its owner or operator can act.</p><h2>Report a concern</h2><p>Contact your Space administrator or {contact()}. Identify the Space, the user or content involved and the approximate time. Share only the evidence you choose and are entitled to disclose; do not send recovery secrets. If someone is in immediate danger, contact emergency services.</p><h2>Protecting children</h2><p>Child sexual abuse and exploitation are prohibited in every form. Do not circulate illegal material to report it. Provide a description or lawful reference and contact the relevant authorities where appropriate. Send child-safety concerns to elonow@9bits.com without forwarding illegal material. The publisher reviews reports and may refer suspected criminal activity to the competent authorities as required by law.</p><h2>Operator responsibilities</h2><p>Company Space operators are responsible for responding to reports, enforcing their membership policies and complying with applicable law. For publisher-operated services, send reports to elonow@9bits.com. Encryption is not an excuse to ignore a report made by a participant.</p><h2>Enforcement</h2><p>The responsible operator may investigate reports, restrict access and cooperate with lawful requests. Measures should be proportionate and respect the rights of those involved. Contact support if you believe an action was mistaken.</p>
''')
}


def main():
    (SITE / "LICENSE.txt").write_bytes((ROOT / "LICENSE").read_bytes())
    for destination, theme, prefix in [("index.html", "light", "./"), ("light/index.html", "light", "../"), ("dark/index.html", "dark", "../")]:
        path = SITE / destination
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(shell("Private team communication", "Open-source team communication with encrypted messages, Spaces, files and live sessions. Explore your hosting options and clear privacy boundaries.", homepage(prefix), prefix, theme))
    for slug, (title, description, content) in LEGAL.items():
        path = SITE / slug / "index.html"
        path.parent.mkdir(parents=True, exist_ok=True)
        body = f'<article class="legal-page"><p class="eyebrow">ELO.NOW / INFORMATION</p><h1>{title}</h1>{content}</article>'
        path.write_text(shell(title, description, body, "../", "light", legal=True, path=f"/{slug}/"))
    urls = [ORIGIN + "/"] + [f"{ORIGIN}/{slug}/" for slug in LEGAL]
    (SITE / "sitemap.xml").write_text('<?xml version="1.0" encoding="UTF-8"?>\n'
        + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + ''.join(f"  <url><loc>{esc(url)}</loc></url>\n" for url in urls) + '</urlset>\n')
    (SITE / "robots.txt").write_text(f"User-agent: *\nAllow: /\n\nSitemap: {ORIGIN}/sitemap.xml\n")
    # Bundle plain text from the same English source. No HTML/Markdown reader or
    # network dependency is needed in the mobile application.
    catalog = {}
    for slug, (title, _, content) in LEGAL.items():
        catalog[f"legal.document.{slug}.title"] = title
        document = PlainDocument()
        document.feed(content)
        catalog[f"legal.document.{slug}.body"] = document.text()
    catalog["legal.version"] = hashlib.sha256(
        (LEGAL["terms"][2] + LEGAL["community"][2]).encode()
    ).hexdigest()[:16]
    (ROOT / "apps/desktop/src/locales/legal.en.json").write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n"
    )
    print("Built 3 product pages, 5 support/legal pages and the offline app catalog.")


if __name__ == "__main__":
    main()
