#!/usr/bin/env python3
"""Copy the approved, already-generated elo icons into initialized mobile projects."""
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
TAURI = ROOT / "apps/desktop/src-tauri"


def main() -> None:
    copied = 0
    for platform, destination in (
        ("android", TAURI / "gen/android/app/src/main/res"),
        ("ios", TAURI / "gen/apple/Assets.xcassets/AppIcon.appiconset"),
    ):
        if not destination.is_dir():
            raise SystemExit(f"Initialize the {platform} project before copying icons")
        if platform == "android":
            # Remove only superseded launcher variants generated by Tauri.
            # The minimum supported Android already understands adaptive icons.
            for legacy in destination.glob("mipmap-*/*"):
                if legacy.name in {"ic_launcher.png", "ic_launcher_round.png", "ic_launcher_foreground.png"} or (
                    legacy.parent.name == "mipmap-anydpi-v26"
                    and legacy.name in {"ic_launcher.xml", "ic_launcher_round.xml"}
                ):
                    legacy.unlink()
            for folder in destination.glob("mipmap-*"):
                if not any(folder.iterdir()):
                    folder.rmdir()
        source = TAURI / "icons" / platform
        for original in sorted(source.rglob("*")):
            if original.is_file():
                # Android 27+ uses adaptive vector icons. PNGs are retained
                # outside packaged resources as sources for store artwork.
                if platform == "android" and original.suffix == ".png":
                    continue
                target = destination / original.relative_to(source)
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(original, target)
                copied += 1
    # The layered iOS icon opts out of automatic glass effects on the logo.
    # Keep the PNG asset catalog as the fallback for older iOS versions.
    shutil.copytree(
        TAURI / "icons/AppIcon.icon",
        TAURI / "gen/apple/AppIcon.icon",
        dirs_exist_ok=True,
    )
    print(f"Copied {copied} approved icon assets; original brandbook files unchanged.")


if __name__ == "__main__":
    main()
